package com.bookstore.entity;
// Generated 2 May, 2019 6:42:24 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "bookstore")
@NamedQueries({ @NamedQuery(name = "Review.listAll", query = "Select r from Review r"),
		@NamedQuery(name = "Review.mostFavouredBooks", query = "SELECT r.book FROM Review r "
				+ "GROUP BY r.book.bookId HAVING AVG(r.rating) >= 4.0 " + "ORDER BY COUNT(r.book.bookId) DESC, AVG(r.rating) DESC"),
		@NamedQuery(name = "Review.countAll", query = "Select count(*) from Review r"),
		@NamedQuery(name = "Review.findByCustomerAndBook", query = "Select r from Review r where r.customer.customerId = :customerId AND r.book.bookId = :bookId"),
		@NamedQuery(name = "Review.recentReviews", query = "Select r from Review r order by r.reviewOn"),
})
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Book book;
	private Customer customer;
	private String comment;
	private float rating;
	private Date reviewOn;
	private String headline;

	public Review() {
	}

	public Review(Book book, Customer customer, String comment, float rating, Date reviewOn, String headline) {
		this.book = book;
		this.customer = customer;
		this.comment = comment;
		this.rating = rating;
		this.reviewOn = reviewOn;
		this.headline = headline;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "comment", nullable = false, length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "rating", nullable = false, precision = 12, scale = 0)
	public float getRating() {
		return this.rating;
	}

	public void setRating(float rating) {
		this.rating = rating;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_on", nullable = false, length = 26)
	public Date getReviewOn() {
		return this.reviewOn;
	}

	public void setReviewOn(Date reviewOn) {
		this.reviewOn = reviewOn;
	}

	@Column(name = "headline", nullable = false, length = 45)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

}
