package com.bookstore.entity;
// Generated 2 May, 2019 6:42:24 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "bookstore", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({ @NamedQuery(name = "Users.findAll", query = "Select u from Users u ORDER BY u.fullName"),
	@NamedQuery(name = "Users.countAll", query = "Select Count(*) from Users u"),
	@NamedQuery(name = "Users.findByEmail", query = "Select u from Users u where u.email = :email"),
	@NamedQuery(name = "Users.findByID", query = "Select u from Users u where u.userId = :id"),
	@NamedQuery(name = "Users.login", query = "Select u from Users u where u.email = :email and u.password = :password") 
})
public class Users implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String fullName;
	private String password;

	public Users() {
	}

	public Users(int userId, String email, String fullName, String password) {
		this.userId = userId;
		this.email = email;
		this.fullName = fullName;
		this.password = password;
	}

	public Users(String email, String fullName, String password) {
		this.email = email;
		this.fullName = fullName;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "full_name", nullable = false)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
